global: 
  smtp_smarthost: 'smtp.xxx.com:25'
  smtp_from: 'xxx'
  smtp_auth_username: 'xxx'
  smtp_auth_password: 'xxx'

templates:
  - '/etc/alertmanager/template/alert.tmpl'

route:
  group_by: ['alertname']
  group_interval: 1m
  # 重复发送通知的间隔时间
  repeat_interval: 5m
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
    - to: 'xxx'
      html: '{{ template "email.alert.html" . }}'
      headers: { Subject: 'Project name : {{ template "__subject" . }}' }
      send_resolved: true
