global:
  scrape_interval: 5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout: 4s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'host_exporter'
    static_configs:
    - targets: ['1.1.1.1:9100']

  - job_name: 'rabbitmq_exporter'
    static_configs:
    - targets: ['1.1.1.1:9419']

  - job_name: 'process_exporter'
    static_configs:
    - targets: ['1.1.1.1:9256']

  - job_name: 'citaMonitorAgent_exporter'
    static_configs:
    - targets: ['1.1.1.1:1920','1.1.1.1:1921','1.1.1.1:1922','1.1.1.1:1923']
