version: '3'
services:
  prometheus:
    user: root
    image: prom/prometheus:v2.6.0
    container_name: cita_monitor_server_prometheus
    hostname: prometheus_server
    privileged: true
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/alert.rules:/etc/prometheus/alert.rules
      - ./data:/etc/prometheus/data
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - alertmanager
    ports:
      - '${PROMETHEUS_HOSTPORT}:${PROMETHEUS_CONTAINERPORT}'

  alertmanager:
    image: prom/alertmanager:v0.15.3
    container_name: cita_monitor_server_alertmanager
    hostname: prometheus_alertmanager_server
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./config/alert.tmpl:/etc/alertmanager/template/alert.tmpl
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
      - '${ALERTMANAGER_HOSTPORT}:${ALERTMANAGER_CONTAINERPORT}'

  grafana:
    user: root
    build: ./grafana
    image: cryptape/grafana:5.4.2
    container_name: cita_monitor_server_grafana
    hostname: grafana_server
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
    volumes:
      - ./config/grafana:/etc/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/grafanadb:/var/lib/grafana/grafanadb
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    depends_on:
      - prometheus
    ports:
      - '${GRAFANA_HOSTPORT}:${GRAFANA_CONTAINERPORT}'

volumes:
  grafana_data: {}
  prometheus_data: {}

