version: "3"
services:

  prometheus_host_exporter:
    image: prom/node-exporter:v0.17.0
    hostname: host_exporter
    container_name: citamon_agent_host_exporter
    ports:
      - "${HOST_HOSTPORT}:${HOST_CONTAINERPORT}"
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/host/rootfs
      - /etc/localtime:/etc/localtime
    command: "--path.procfs='/host/proc' --path.sysfs='/host/sys' --path.rootfs='/host/rootfs'"

  prometheus_process_exporter:
    image: ncabatoff/process-exporter:0.4.0
    hostname: process_exporter
    container_name: citamon_agent_process_exporter
    ports:
      - "${PROCESS_HOSTPORT}:${PROCESS_CONTAINERPORT}"
    volumes:
      - /proc:/host/proc
      - ./process_exporter_config:/config
      - /etc/localtime:/etc/localtime
    command: "--procfs /host/proc --config.path /config/process_list.yml"

  prometheus_rabbitmq_exporter:
    image: kbudde/rabbitmq-exporter:1.0.0-RC
    hostname: rabbitmq_exporter
    container_name: citamon_agent_rabbitmq_exporter
    network_mode: "host"
    ports:
      - "${RABBITMQ_HOSTPORT}:${RABBITMQ_CONTAINERPORT}"
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - "RABBIT_CAPABILITIES=bert,no_sort"
      - "PUBLISH_PORT=${RABBITMQ_CONTAINERPORT}"

  prometheus_cita_exporter:
    build: ./cita_exporter
    image: citamon/agent-cita-exporter
    hostname: ${HOSTNAME}
    container_name: citamon_agent_cita_exporter_${NODE_IP}_${NODE_PORT}
    pid: "host"
    ports:
      - "${AGENT_HOSTPORT}:${AGENT_CONTAINERPORT}"
    volumes:
      - ${NODE_DIR}:${NODE_DIR}:ro
      - ${SOFT_PATH}:${SOFT_PATH}:ro
      - ./cita_monitor_agent.py:/config/cita_monitor_agent.py:ro
      - /etc/localtime:/etc/localtime
    environment:
      - NODE_IP_PORT=${NODE_IP}:${NODE_PORT}
      - NODE_DIR

