name: pipeline of agent

on: [push]

jobs:
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.5.4'
      - uses: actions/checkout@v2
      - run: pwd && ls -a -l
      - run: make deps
      - run: make test
        
  code_audit:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.5.4'
      - uses: actions/checkout@v2
      - run: make deps
      - run: make code-quality
          
  build:
    needs: [test, code_audit]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: agent
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get install -y docker docker-compose
          sudo systemctl unmask docker.service
          sudo systemctl start docker.service
          sudo docker --version
          sudo cp -v .env.example .env
          sudo docker-compose -f docker-compose-with-build.yml build
          sudo docker-compose -f docker-compose-with-build.yml push

