name: pipeline of agent

on: [push]

jobs:
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.5.4'
      - run: make deps
      - run: make test
        
  code_audit:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.5.4'
      - run: make deps
      - run: make code-quality
          
  build:
    needs: [test, code_audit]
    runs-on: ubuntu-latest
    defaults:
      run: bash
      working-directory: agent
    steps:
      - run: apt-get install docker && apt-get install docker-compose
      - run: docker-compose -f docker-compose-with-build.yml build
      - run: docker-compose -f docker-compose-with-build.yml push

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: echo "not implemented."
