name: pipeline of agent

on: [push]

jobs:
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.5.4'
      - uses: actions/checkout@v2
      - run: pwd && ls -a -l
      - run: make deps
      - run: make test
        
  code_audit:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.5.4'
      - uses: actions/checkout@v2
      - run: make deps
      - run: make code-quality
          
  build:
    needs: [test, code_audit]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: agent
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
        env:
          DOCKERHUB_USERNAME: "${{ secrets.DOCKERHUB_USERNAME }}"
          DOCKERHUB_PASSWORD: "${{ secrets.DOCKERHUB_PASSWORD }}"
      - run: |
          sudo apt-get install -y docker-compose
          sudo cp -v .env.example .env
          sudo docker-compose -f docker-compose-with-build.yml build
          echo "${DOCKERHUB_PASSWORD}"| sudo docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
          sudo docker-compose -f docker-compose-with-build.yml push

